name: micro-reddit

type: rails

up:
  - homebrew:
    - openssl
    - shopify/shopify/mysql-client:
        or:        [mysql]
        conflicts: [mysql-connector-c]
    # - another_package
  - ruby: 2.4.2
  - bundler
  - railgun
  - database:
      bootstrap: bin/rails db:create db:migrate db:schema:load
      migrate: bin/rails db:migrate db:test:prepare
      host: micro-reddit.railgun
      user: root
      password: ''
      database: micro-reddit_development

server:
  port: 42415

commands:
  console: bin/rails console
  test:
    syntax:
      argument: file
      optional: args...
    run:    bin/rails test

# These use fuzzy-matching, so you can (e.g.) `dev open app`
open:
  "My Application": https://micro-reddit.myshopify.io
